### PR TITLE
Fix gosec

### LINKED ISSUE #456: Fix and/or ignore gosec annotations
The gosec scan added in #431 generated several annotations of possible vulnerabilities.
The annotations can be found in the "changed files" section of any open PR, e.g.:
https://github.com/kubernetes-sigs/kpng/pull/440/files

Now, we need to check if they make sense and either fix them or ignore false positives like in https://github.com/kubernetes-sigs/kpng/pull/435

[Its documentation](https://github.com/securego/gosec) details about rules, running locally, etc.

### PR DESCRIPTION
**Pull request by brunopecampos**
Signed-off-by: brunopecampos <brunopecampos@protonmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes and ignores some of the vulnerabilities found by Gosec

#### Which issue(s) this PR fixes:

fixes #456

#### Special notes for your reviewer:

I split the vulnerabilities found in three groups:
- Fixable: G114 (Use of net/http's ListenAndServe function has no support for setting timeouts. Added timeouts), G112 (Potential Slowris attack. Also added timeout to http listen), G402 (TLS MinVersion too low. Set it too 1.2, which was released in 2008 ) and G404 (Use of weak random number generator. Changed from math/rand to crypto/rand) . They were fixed in the first three commits.
- Already Ignored: G101, G104, G304, G306, G307.
- Ignorable: G204 (Subprocess launched with variable), G601 (Implicit memory aliasing in for loop). The last one occurs in a Go generated file.

Did the tests before and after the commits and they gave the same errors, so i concluded it was fine (hopefully).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: backends/userspacelin/port_allocator.go [hunk 1]
```diff
@@ -116,7 +114,12 @@ func (r *rangeAllocator) nextFreePort() int {
 	defer r.lock.Unlock()
 
 	// choose random port
-	j := r.rand.Intn(r.Size)
+	nBig, err := rand.Int(rand.Reader, big.NewInt(int64(r.Size)))
+  if err != nil {
```
Comment (jaehnri) [inline backends/userspacelin/port_allocator.go:118]: Fix the indentation here

File: examples/userspace-proxier/service.go [hunk 2]
```diff
@@ -47,7 +42,11 @@ func (svc *service) RandomEndpoint() string {
 		return ""
 	}
 
-	return eps[rand.Intn(len(eps))].targetIP
+	nBig, err := rand.Int(rand.Reader, big.NewInt(int64(len(eps))))
+  if err != nil {
```
Comment (jaehnri) [inline examples/userspace-proxier/service.go:46]: Fix the indentation here

File: server/cmd/kpng-backend-torture/main.go [hunk 3]
```diff
@@ -46,8 +47,12 @@ var (
 func main() {
 	flag.Parse()
 
-	rand.Seed(time.Now().UnixNano())
-	instanceID = rand.Uint64()
+	var b [8]byte
+  _, err := rand.Read(b[:])
```
Comment (jaehnri) [inline server/cmd/kpng-backend-torture/main.go:51]: Fix the indentation here

**Comment by jaehnri** [comment]
If this issue fixes all current `gosec` annotations, you might use "fixes #<ISSUE_NUMBER>" in the PR's description to automatically close the upstream issue

File: backends/userspacelin/port_allocator.go [hunk 4]
```diff
@@ -116,7 +114,12 @@ func (r *rangeAllocator) nextFreePort() int {
 	defer r.lock.Unlock()
 
 	// choose random port
-	j := r.rand.Intn(r.Size)
+	nBig, err := rand.Int(rand.Reader, big.NewInt(int64(r.Size)))
```
[the remark this answers is not in the document]
Comment (brunopecampos) [reply backends/userspacelin/port_allocator.go:117]: The type of r.Size() is int and NewInt requires an int64, so it can't work without the casting.

**Comment by brunopecampos** [comment]
> If this issue fixes all current `gosec` annotations, you might use "fixes #<ISSUE_NUMBER>" in the PR's description to automatically close the upstream issue.
> 
> Also, we'll disable the `gosec` scanner in our CI (see #457) because it is blocking the merge of other PRs. Would you please send the output of gosec locally with the same parameters used in the CI? Thanks!!
> 
> /ok-to-test

I've edited the PR description. Thanks for the tip!

After the last commit, running the gosec scanner with the parameters in security.yaml gives me the following gosec-results.sarif:

`{
	"runs": [
		{
			"results": [],
			"taxonomies": [
				{
					"downloadUri": "https://cwe.mitre.org/data/xml/cwec_v4.4.xml.zip",
					"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
					"informationUri": "https://cwe.mitre.org/data/published/cwe_v4.4.pdf/",
					"isComprehensive": true,
					"language": "en",
					"minimumRequiredLocalizedDataSemanticVersion": "4.4",
					"name": "CWE",
					"organization": "MITRE",
					"releaseDateUtc": "2021-03-15",
					"shortDescription": {
						"text": "The MITRE Common Weakness Enumeration"
					},
					"version": "4.4"
				}
			],
			"tool": {
				"driver": {
					"guid": "8b518d5f-906d-39f9-894b-d327b1a421c5",
					"informationUri": "https://github.com/securego/gosec/",
					"name": "gosec",
					"semanticVersion": "2.14.0",
					"supportedTaxonomies": [
						{
							"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
							"name": "CWE"
						}
					],
					"version": "2.14.0"
				}
			}
		}
	],
	"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
	"version": "2.1.0"
}`

As you can see, 0 warnings.

**Review by jayunit100 — APPROVED** [review]
